name: build
run-name: build
on: [push]
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Build
        run: |
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install -y git make libjack-dev libftgl-dev libglu1-mesa-dev xxd g++
            make
            ls build
            ls build/tuneBfree.lv2
      - name: Test
        run: |
            git clone https://github.com/ODDSound/MTS-ESP.git ~/MTS-ESP
            sudo mkdir -p /usr/local/lib
            sudo cp ~/MTS-ESP/libMTS/Linux/x86_64/libMTS.so /usr/local/lib/
            python3 -m venv .env
            source .env/bin/activate
            git clone --recurse-submodules https://github.com/narenratan/mtsespy.git ~/mtsespy
            python3 -m pip install ~/mtsespy
            python3 -m pip install pytest
            pytest tests
      - uses: actions/upload-artifact@v4
        with:
            name: build_linux
            path: build
  build_mac:
    runs-on: macos-14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Build
        run: |
            brew install jack freeglut ftgl bzip2 pkg-config
            make
            ls build
            ls build/tuneBfree.lv2
      - name: Test
        run: |
            git clone https://github.com/ODDSound/MTS-ESP.git ~/MTS-ESP
            sudo mkdir -p "/Library/Application Support/MTS-ESP/"
            sudo cp ~/MTS-ESP/libMTS/Mac/x86_64_ARM/libMTS.dylib "/Library/Application Support/MTS-ESP/libMTS.dylib"
            python3 -m venv .env
            source .env/bin/activate
            git clone --recurse-submodules https://github.com/narenratan/mtsespy.git ~/mtsespy
            python3 -m pip install ~/mtsespy
            python3 -m pip install pytest
            pytest tests
      - uses: actions/upload-artifact@v4
        with:
            name: build_mac
            path: build
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
                git
                make
                vim
                mingw-w64-ucrt-x86_64-gcc
                mingw-w64-ucrt-x86_64-jack2
                mingw-w64-ucrt-x86_64-freeglut
                mingw-w64-ucrt-x86_64-ftgl
                mingw-w64-ucrt-x86_64-pkg-config
      - name: Build
        run: |
          make
          ls build
          ls build/tuneBfree.lv2
      - name: Test
        run: |
            git clone https://github.com/narenratan/libjack64_dll.git ~/libjack64_dll
            cp ~/libjack64_dll/libjack64.dll .
            python3 -m venv .env
            source .env/bin/activate
            python3 -m pip install pytest
            pytest tests/test_basic.py
      - uses: actions/upload-artifact@v4
        with:
            name: build_windows
            path: build
  checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - run: make formatcheck
      - name: Build
        run: |
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install -y git make libjack-dev libftgl-dev libglu1-mesa-dev xxd g++
            export SANITIZE=yes
            make
      - name: Test with sanitizers
        run: |
            git clone https://github.com/ODDSound/MTS-ESP.git ~/MTS-ESP
            sudo mkdir -p /usr/local/lib
            sudo cp ~/MTS-ESP/libMTS/Linux/x86_64/libMTS.so /usr/local/lib/
            python3 -m venv .env
            source .env/bin/activate
            git clone --recurse-submodules https://github.com/narenratan/mtsespy.git ~/mtsespy
            python3 -m pip install ~/mtsespy
            python3 -m pip install pytest
            pytest tests
