name: checks
run-name: checks
on: [push]
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: make formatcheck
      - run: ./build_scripts/build_linux.sh
      - uses: actions/upload-artifact@v4
        with:
            name: build_linux
            path: build
