name: checks
run-name: checks
on: [push]
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: make formatcheck
      - run: ./build_scripts/build_linux.sh
      - uses: actions/upload-artifact@v4
        with:
            name: build_linux
            path: build
  build_mac:
    runs-on: macos-14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./build_scripts/build_mac.sh
      - uses: actions/upload-artifact@v4
        with:
            name: build_mac
            path: build
